version: '3'
services:
  permission-service:
    build: .
    env_file:
      - ../kdrive.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
      