// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package permission

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_NONE  Role = 0
	Role_OWNER Role = 1
	Role_WRITE Role = 2
	Role_READ  Role = 3
)

var Role_name = map[int32]string{
	0: "NONE",
	1: "OWNER",
	2: "WRITE",
	3: "READ",
}

var Role_value = map[string]int32{
	"NONE":  0,
	"OWNER": 1,
	"WRITE": 2,
	"READ":  3,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

type CreatePermissionRequest struct {
	// The ID of the file which is being permitted.
	FileID string `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// The ID of the user that's given the permission.
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// The role of the permission.
	Role                 Role     `protobuf:"varint,3,opt,name=role,proto3,enum=permission.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePermissionRequest) Reset()         { *m = CreatePermissionRequest{} }
func (m *CreatePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePermissionRequest) ProtoMessage()    {}
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

func (m *CreatePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePermissionRequest.Unmarshal(m, b)
}
func (m *CreatePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePermissionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePermissionRequest.Merge(m, src)
}
func (m *CreatePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePermissionRequest.Size(m)
}
func (m *CreatePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePermissionRequest proto.InternalMessageInfo

func (m *CreatePermissionRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *CreatePermissionRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreatePermissionRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NONE
}

type DeletePermissionRequest struct {
	// The ID of the file which is being permitted.
	FileID string `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// The ID of the user that's given the permission.
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePermissionRequest) Reset()         { *m = DeletePermissionRequest{} }
func (m *DeletePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePermissionRequest) ProtoMessage()    {}
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{1}
}

func (m *DeletePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePermissionRequest.Unmarshal(m, b)
}
func (m *DeletePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePermissionRequest.Marshal(b, m, deterministic)
}
func (m *DeletePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePermissionRequest.Merge(m, src)
}
func (m *DeletePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePermissionRequest.Size(m)
}
func (m *DeletePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePermissionRequest proto.InternalMessageInfo

func (m *DeletePermissionRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *DeletePermissionRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type PermissionObject struct {
	// The ID of the permission.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the file which is being pemitted.
	FileID string `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// The ID of the user that's given the permission.
	UserID string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	// The role of the permission.
	Role                 Role     `protobuf:"varint,4,opt,name=role,proto3,enum=permission.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionObject) Reset()         { *m = PermissionObject{} }
func (m *PermissionObject) String() string { return proto.CompactTextString(m) }
func (*PermissionObject) ProtoMessage()    {}
func (*PermissionObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{2}
}

func (m *PermissionObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionObject.Unmarshal(m, b)
}
func (m *PermissionObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionObject.Marshal(b, m, deterministic)
}
func (m *PermissionObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionObject.Merge(m, src)
}
func (m *PermissionObject) XXX_Size() int {
	return xxx_messageInfo_PermissionObject.Size(m)
}
func (m *PermissionObject) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionObject.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionObject proto.InternalMessageInfo

func (m *PermissionObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PermissionObject) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *PermissionObject) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PermissionObject) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NONE
}

type GetPermissionRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionRequest) Reset()         { *m = GetPermissionRequest{} }
func (m *GetPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionRequest) ProtoMessage()    {}
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{3}
}

func (m *GetPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionRequest.Unmarshal(m, b)
}
func (m *GetPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionRequest.Merge(m, src)
}
func (m *GetPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionRequest.Size(m)
}
func (m *GetPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionRequest proto.InternalMessageInfo

func (m *GetPermissionRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *GetPermissionRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetFilePermissionsRequest struct {
	// The ID of the file which is being permitted.
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilePermissionsRequest) Reset()         { *m = GetFilePermissionsRequest{} }
func (m *GetFilePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilePermissionsRequest) ProtoMessage()    {}
func (*GetFilePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{4}
}

func (m *GetFilePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilePermissionsRequest.Unmarshal(m, b)
}
func (m *GetFilePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilePermissionsRequest.Marshal(b, m, deterministic)
}
func (m *GetFilePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilePermissionsRequest.Merge(m, src)
}
func (m *GetFilePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilePermissionsRequest.Size(m)
}
func (m *GetFilePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilePermissionsRequest proto.InternalMessageInfo

func (m *GetFilePermissionsRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

type GetFilePermissionsResponse struct {
	// Array of user roles.
	Permissions          []*GetFilePermissionsResponse_UserRole `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetFilePermissionsResponse) Reset()         { *m = GetFilePermissionsResponse{} }
func (m *GetFilePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFilePermissionsResponse) ProtoMessage()    {}
func (*GetFilePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{5}
}

func (m *GetFilePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilePermissionsResponse.Unmarshal(m, b)
}
func (m *GetFilePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilePermissionsResponse.Marshal(b, m, deterministic)
}
func (m *GetFilePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilePermissionsResponse.Merge(m, src)
}
func (m *GetFilePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFilePermissionsResponse.Size(m)
}
func (m *GetFilePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilePermissionsResponse proto.InternalMessageInfo

func (m *GetFilePermissionsResponse) GetPermissions() []*GetFilePermissionsResponse_UserRole {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// The role of a user.
type GetFilePermissionsResponse_UserRole struct {
	// The user ID.
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// The role of the user.
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=permission.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilePermissionsResponse_UserRole) Reset()         { *m = GetFilePermissionsResponse_UserRole{} }
func (m *GetFilePermissionsResponse_UserRole) String() string { return proto.CompactTextString(m) }
func (*GetFilePermissionsResponse_UserRole) ProtoMessage()    {}
func (*GetFilePermissionsResponse_UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{5, 0}
}

func (m *GetFilePermissionsResponse_UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilePermissionsResponse_UserRole.Unmarshal(m, b)
}
func (m *GetFilePermissionsResponse_UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilePermissionsResponse_UserRole.Marshal(b, m, deterministic)
}
func (m *GetFilePermissionsResponse_UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilePermissionsResponse_UserRole.Merge(m, src)
}
func (m *GetFilePermissionsResponse_UserRole) XXX_Size() int {
	return xxx_messageInfo_GetFilePermissionsResponse_UserRole.Size(m)
}
func (m *GetFilePermissionsResponse_UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilePermissionsResponse_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilePermissionsResponse_UserRole proto.InternalMessageInfo

func (m *GetFilePermissionsResponse_UserRole) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetFilePermissionsResponse_UserRole) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NONE
}

type IsPermittedRequest struct {
	// The ID of the file which is being permitted.
	FileID string `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// The ID of the user that's given the permission.
	UserID string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	// The role of the permission.
	Role                 Role     `protobuf:"varint,3,opt,name=role,proto3,enum=permission.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsPermittedRequest) Reset()         { *m = IsPermittedRequest{} }
func (m *IsPermittedRequest) String() string { return proto.CompactTextString(m) }
func (*IsPermittedRequest) ProtoMessage()    {}
func (*IsPermittedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{6}
}

func (m *IsPermittedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsPermittedRequest.Unmarshal(m, b)
}
func (m *IsPermittedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsPermittedRequest.Marshal(b, m, deterministic)
}
func (m *IsPermittedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsPermittedRequest.Merge(m, src)
}
func (m *IsPermittedRequest) XXX_Size() int {
	return xxx_messageInfo_IsPermittedRequest.Size(m)
}
func (m *IsPermittedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsPermittedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsPermittedRequest proto.InternalMessageInfo

func (m *IsPermittedRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *IsPermittedRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *IsPermittedRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NONE
}

type IsPermittedResponse struct {
	Permitted            bool     `protobuf:"varint,1,opt,name=permitted,proto3" json:"permitted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsPermittedResponse) Reset()         { *m = IsPermittedResponse{} }
func (m *IsPermittedResponse) String() string { return proto.CompactTextString(m) }
func (*IsPermittedResponse) ProtoMessage()    {}
func (*IsPermittedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{7}
}

func (m *IsPermittedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsPermittedResponse.Unmarshal(m, b)
}
func (m *IsPermittedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsPermittedResponse.Marshal(b, m, deterministic)
}
func (m *IsPermittedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsPermittedResponse.Merge(m, src)
}
func (m *IsPermittedResponse) XXX_Size() int {
	return xxx_messageInfo_IsPermittedResponse.Size(m)
}
func (m *IsPermittedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsPermittedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsPermittedResponse proto.InternalMessageInfo

func (m *IsPermittedResponse) GetPermitted() bool {
	if m != nil {
		return m.Permitted
	}
	return false
}

type GetUserPermissionsRequest struct {
	// The ID of the user to get its permissions.
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// Filter permissions where the user was given a role of owner or not.
	IsOwner              bool     `protobuf:"varint,2,opt,name=isOwner,proto3" json:"isOwner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserPermissionsRequest) Reset()         { *m = GetUserPermissionsRequest{} }
func (m *GetUserPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserPermissionsRequest) ProtoMessage()    {}
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{8}
}

func (m *GetUserPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPermissionsRequest.Unmarshal(m, b)
}
func (m *GetUserPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPermissionsRequest.Merge(m, src)
}
func (m *GetUserPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserPermissionsRequest.Size(m)
}
func (m *GetUserPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPermissionsRequest proto.InternalMessageInfo

func (m *GetUserPermissionsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetUserPermissionsRequest) GetIsOwner() bool {
	if m != nil {
		return m.IsOwner
	}
	return false
}

type GetUserPermissionsResponse struct {
	// Array of files and their role.
	Permissions          []*GetUserPermissionsResponse_FileRole `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetUserPermissionsResponse) Reset()         { *m = GetUserPermissionsResponse{} }
func (m *GetUserPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserPermissionsResponse) ProtoMessage()    {}
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{9}
}

func (m *GetUserPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPermissionsResponse.Unmarshal(m, b)
}
func (m *GetUserPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPermissionsResponse.Merge(m, src)
}
func (m *GetUserPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserPermissionsResponse.Size(m)
}
func (m *GetUserPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPermissionsResponse proto.InternalMessageInfo

func (m *GetUserPermissionsResponse) GetPermissions() []*GetUserPermissionsResponse_FileRole {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// The file of the permission and its role.
type GetUserPermissionsResponse_FileRole struct {
	// The file ID.
	FileID string `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// The role of the file permission.
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=permission.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserPermissionsResponse_FileRole) Reset()         { *m = GetUserPermissionsResponse_FileRole{} }
func (m *GetUserPermissionsResponse_FileRole) String() string { return proto.CompactTextString(m) }
func (*GetUserPermissionsResponse_FileRole) ProtoMessage()    {}
func (*GetUserPermissionsResponse_FileRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{9, 0}
}

func (m *GetUserPermissionsResponse_FileRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPermissionsResponse_FileRole.Unmarshal(m, b)
}
func (m *GetUserPermissionsResponse_FileRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPermissionsResponse_FileRole.Marshal(b, m, deterministic)
}
func (m *GetUserPermissionsResponse_FileRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPermissionsResponse_FileRole.Merge(m, src)
}
func (m *GetUserPermissionsResponse_FileRole) XXX_Size() int {
	return xxx_messageInfo_GetUserPermissionsResponse_FileRole.Size(m)
}
func (m *GetUserPermissionsResponse_FileRole) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPermissionsResponse_FileRole.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPermissionsResponse_FileRole proto.InternalMessageInfo

func (m *GetUserPermissionsResponse_FileRole) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *GetUserPermissionsResponse_FileRole) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_NONE
}

type DeleteFilePermissionsRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFilePermissionsRequest) Reset()         { *m = DeleteFilePermissionsRequest{} }
func (m *DeleteFilePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFilePermissionsRequest) ProtoMessage()    {}
func (*DeleteFilePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{10}
}

func (m *DeleteFilePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFilePermissionsRequest.Unmarshal(m, b)
}
func (m *DeleteFilePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFilePermissionsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFilePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFilePermissionsRequest.Merge(m, src)
}
func (m *DeleteFilePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFilePermissionsRequest.Size(m)
}
func (m *DeleteFilePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFilePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFilePermissionsRequest proto.InternalMessageInfo

func (m *DeleteFilePermissionsRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

type DeleteFilePermissionsResponse struct {
	Permissions          []*PermissionObject `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeleteFilePermissionsResponse) Reset()         { *m = DeleteFilePermissionsResponse{} }
func (m *DeleteFilePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFilePermissionsResponse) ProtoMessage()    {}
func (*DeleteFilePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{11}
}

func (m *DeleteFilePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFilePermissionsResponse.Unmarshal(m, b)
}
func (m *DeleteFilePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFilePermissionsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFilePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFilePermissionsResponse.Merge(m, src)
}
func (m *DeleteFilePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFilePermissionsResponse.Size(m)
}
func (m *DeleteFilePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFilePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFilePermissionsResponse proto.InternalMessageInfo

func (m *DeleteFilePermissionsResponse) GetPermissions() []*PermissionObject {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterEnum("permission.Role", Role_name, Role_value)
	proto.RegisterType((*CreatePermissionRequest)(nil), "permission.CreatePermissionRequest")
	proto.RegisterType((*DeletePermissionRequest)(nil), "permission.DeletePermissionRequest")
	proto.RegisterType((*PermissionObject)(nil), "permission.PermissionObject")
	proto.RegisterType((*GetPermissionRequest)(nil), "permission.GetPermissionRequest")
	proto.RegisterType((*GetFilePermissionsRequest)(nil), "permission.GetFilePermissionsRequest")
	proto.RegisterType((*GetFilePermissionsResponse)(nil), "permission.GetFilePermissionsResponse")
	proto.RegisterType((*GetFilePermissionsResponse_UserRole)(nil), "permission.GetFilePermissionsResponse.UserRole")
	proto.RegisterType((*IsPermittedRequest)(nil), "permission.IsPermittedRequest")
	proto.RegisterType((*IsPermittedResponse)(nil), "permission.IsPermittedResponse")
	proto.RegisterType((*GetUserPermissionsRequest)(nil), "permission.GetUserPermissionsRequest")
	proto.RegisterType((*GetUserPermissionsResponse)(nil), "permission.GetUserPermissionsResponse")
	proto.RegisterType((*GetUserPermissionsResponse_FileRole)(nil), "permission.GetUserPermissionsResponse.FileRole")
	proto.RegisterType((*DeleteFilePermissionsRequest)(nil), "permission.DeleteFilePermissionsRequest")
	proto.RegisterType((*DeleteFilePermissionsResponse)(nil), "permission.DeleteFilePermissionsResponse")
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_c837ef01cbda0ad8) }

var fileDescriptor_c837ef01cbda0ad8 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5b, 0x8f, 0xd2, 0x40,
	0x14, 0xa6, 0x85, 0x5d, 0xe1, 0x10, 0x37, 0x93, 0xf1, 0xb2, 0x95, 0xa0, 0x92, 0x7a, 0x09, 0xfa,
	0x80, 0x06, 0x12, 0x1f, 0x4d, 0x8c, 0xb0, 0x6b, 0x1f, 0x84, 0xdd, 0x89, 0x86, 0x47, 0xe3, 0xca,
	0x31, 0xe9, 0xa6, 0x52, 0xec, 0x0c, 0xd1, 0xbf, 0xe3, 0xcf, 0xf0, 0xdf, 0x99, 0x4e, 0x5b, 0x3a,
	0x6d, 0x67, 0xb8, 0x44, 0x7d, 0x63, 0xce, 0x70, 0xbe, 0x6f, 0xbe, 0x73, 0xf9, 0x0a, 0x64, 0x85,
	0xd1, 0x37, 0x9f, 0x73, 0x3f, 0x5c, 0x0e, 0x56, 0x51, 0x28, 0x42, 0x0a, 0x79, 0xc4, 0x0d, 0xe1,
	0xf4, 0x6d, 0x84, 0x9f, 0x05, 0x5e, 0x6c, 0x62, 0x0c, 0xbf, 0xaf, 0x91, 0x0b, 0x7a, 0x17, 0x8e,
	0xbf, 0xfa, 0x01, 0x7a, 0x63, 0xc7, 0xea, 0x59, 0xfd, 0x16, 0x4b, 0x4f, 0x71, 0x7c, 0xcd, 0x31,
	0xf2, 0xc6, 0x8e, 0x9d, 0xc4, 0x93, 0x13, 0x7d, 0x0c, 0x8d, 0x28, 0x0c, 0xd0, 0xa9, 0xf7, 0xac,
	0xfe, 0xc9, 0x90, 0x0c, 0x14, 0x5e, 0x16, 0x06, 0xc8, 0xe4, 0xad, 0xeb, 0xc1, 0xe9, 0x18, 0x03,
	0xfc, 0x07, 0x84, 0xee, 0x4f, 0x20, 0x39, 0xc8, 0xec, 0xea, 0x1a, 0xbf, 0x08, 0x7a, 0x02, 0xb6,
	0xbf, 0x48, 0xf3, 0x6d, 0x7f, 0xa1, 0x60, 0xda, 0x06, 0xcc, 0xba, 0x56, 0x44, 0x63, 0xab, 0x88,
	0x33, 0xb8, 0x7d, 0x8e, 0xe2, 0xef, 0x15, 0x8c, 0xe0, 0xde, 0x39, 0x8a, 0x33, 0x3f, 0x50, 0xaa,
	0xc1, 0x77, 0x80, 0xb9, 0xbf, 0x2d, 0xe8, 0xe8, 0xb2, 0xf8, 0x2a, 0x5c, 0x72, 0xa4, 0x97, 0xd0,
	0xce, 0x1f, 0xcd, 0x1d, 0xab, 0x57, 0xef, 0xb7, 0x87, 0x2f, 0x54, 0x21, 0xe6, 0xe4, 0xc1, 0x47,
	0x8e, 0x91, 0xd4, 0xa9, 0x62, 0x74, 0xde, 0x41, 0x33, 0xbb, 0x50, 0xa4, 0x58, 0xda, 0xc2, 0xd9,
	0x5b, 0x0b, 0x77, 0x0d, 0xd4, 0xe3, 0x92, 0x58, 0x08, 0x5c, 0xfc, 0xdf, 0x49, 0x1b, 0xc1, 0xad,
	0x02, 0x57, 0x5a, 0x9f, 0x2e, 0xb4, 0x56, 0x59, 0x50, 0xf2, 0x35, 0x59, 0x1e, 0x70, 0xdf, 0xcb,
	0x8e, 0xc4, 0x6a, 0xf5, 0x1d, 0xd1, 0x6a, 0x77, 0xe0, 0x86, 0xcf, 0x67, 0x3f, 0x96, 0x18, 0xc9,
	0x87, 0x36, 0x59, 0x76, 0xcc, 0x7a, 0x55, 0xc1, 0x3b, 0xa4, 0x57, 0x86, 0xe4, 0x41, 0xdc, 0x43,
	0x6d, 0xaf, 0xb2, 0x0b, 0x63, 0x5d, 0xf7, 0xeb, 0xd5, 0x2b, 0xe8, 0x26, 0x9b, 0x7a, 0xe0, 0x7c,
	0x7e, 0x82, 0xfb, 0x86, 0xbc, 0x54, 0xf5, 0x6b, 0x9d, 0xea, 0xae, 0xfa, 0x8a, 0xf2, 0x5a, 0x17,
	0x24, 0x3e, 0x7f, 0x09, 0x0d, 0x29, 0xaf, 0x09, 0x8d, 0xe9, 0x6c, 0x3a, 0x21, 0x35, 0xda, 0x82,
	0xa3, 0xd9, 0x7c, 0x3a, 0x61, 0xc4, 0x8a, 0x7f, 0xce, 0x99, 0xf7, 0x61, 0x42, 0xec, 0xf8, 0x9e,
	0x4d, 0xde, 0x8c, 0x49, 0x7d, 0xf8, 0xeb, 0x08, 0x20, 0xc7, 0xa4, 0x73, 0x20, 0x65, 0xd3, 0xa3,
	0x8f, 0x54, 0x7e, 0x83, 0x25, 0x76, 0xb6, 0x3e, 0xd2, 0xad, 0xc5, 0xc0, 0x65, 0x73, 0x2b, 0x02,
	0x1b, 0xac, 0x6f, 0x27, 0xf0, 0x25, 0xdc, 0x2c, 0x18, 0x0e, 0xed, 0x95, 0x86, 0xe4, 0x70, 0x48,
	0x04, 0x5a, 0x35, 0x02, 0xfa, 0x64, 0x97, 0x51, 0x24, 0xe0, 0x4f, 0xf7, 0xf3, 0x93, 0x0d, 0x4d,
	0x69, 0x86, 0x2b, 0x34, 0xfa, 0x85, 0xab, 0xd0, 0x18, 0x56, 0xc1, 0xad, 0xd1, 0x0b, 0x68, 0x2b,
	0xcb, 0x4e, 0x1f, 0xa8, 0x89, 0x55, 0xc7, 0xe9, 0x3c, 0x34, 0xde, 0x6f, 0x10, 0x97, 0x70, 0x47,
	0x3b, 0xc6, 0xb4, 0x5f, 0x6d, 0xa8, 0xa1, 0x4a, 0xcf, 0xf6, 0xf8, 0x67, 0xc6, 0x77, 0x75, 0x2c,
	0x3f, 0xce, 0xa3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xec, 0xa1, 0x66, 0xb0, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PermissionClient interface {
	// CreatePermission creates a new permission and returns it, if permission already exists, update it.
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error)
	// DeletePermission deletes a permission and returns it.
	DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error)
	// GetPermission returns a permission of the user to a file.
	GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error)
	// GetFilePermissions returns the users and their role that have a permission to fileID.
	GetFilePermissions(ctx context.Context, in *GetFilePermissionsRequest, opts ...grpc.CallOption) (*GetFilePermissionsResponse, error)
	// GetUserPermissions returns the files that the user was given permission to,
	// if IsOwner is true, returns the permissions of files that the user has a role of OWNER,
	// otherwise returns the permissions of files that the user has a role that is not OWNER or NONE.
	GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error)
	// IsPermitted returns true if userID is permitted to a fileID with the wanted role.
	IsPermitted(ctx context.Context, in *IsPermittedRequest, opts ...grpc.CallOption) (*IsPermittedResponse, error)
	// DeleteFilePermissions deletes all permissions of a file and returns them.
	DeleteFilePermissions(ctx context.Context, in *DeleteFilePermissionsRequest, opts ...grpc.CallOption) (*DeleteFilePermissionsResponse, error)
}

type permissionClient struct {
	cc *grpc.ClientConn
}

func NewPermissionClient(cc *grpc.ClientConn) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error) {
	out := new(PermissionObject)
	err := c.cc.Invoke(ctx, "/permission.Permission/CreatePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error) {
	out := new(PermissionObject)
	err := c.cc.Invoke(ctx, "/permission.Permission/DeletePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*PermissionObject, error) {
	out := new(PermissionObject)
	err := c.cc.Invoke(ctx, "/permission.Permission/GetPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetFilePermissions(ctx context.Context, in *GetFilePermissionsRequest, opts ...grpc.CallOption) (*GetFilePermissionsResponse, error) {
	out := new(GetFilePermissionsResponse)
	err := c.cc.Invoke(ctx, "/permission.Permission/GetFilePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error) {
	out := new(GetUserPermissionsResponse)
	err := c.cc.Invoke(ctx, "/permission.Permission/GetUserPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) IsPermitted(ctx context.Context, in *IsPermittedRequest, opts ...grpc.CallOption) (*IsPermittedResponse, error) {
	out := new(IsPermittedResponse)
	err := c.cc.Invoke(ctx, "/permission.Permission/IsPermitted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) DeleteFilePermissions(ctx context.Context, in *DeleteFilePermissionsRequest, opts ...grpc.CallOption) (*DeleteFilePermissionsResponse, error) {
	out := new(DeleteFilePermissionsResponse)
	err := c.cc.Invoke(ctx, "/permission.Permission/DeleteFilePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
type PermissionServer interface {
	// CreatePermission creates a new permission and returns it, if permission already exists, update it.
	CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionObject, error)
	// DeletePermission deletes a permission and returns it.
	DeletePermission(context.Context, *DeletePermissionRequest) (*PermissionObject, error)
	// GetPermission returns a permission of the user to a file.
	GetPermission(context.Context, *GetPermissionRequest) (*PermissionObject, error)
	// GetFilePermissions returns the users and their role that have a permission to fileID.
	GetFilePermissions(context.Context, *GetFilePermissionsRequest) (*GetFilePermissionsResponse, error)
	// GetUserPermissions returns the files that the user was given permission to,
	// if IsOwner is true, returns the permissions of files that the user has a role of OWNER,
	// otherwise returns the permissions of files that the user has a role that is not OWNER or NONE.
	GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error)
	// IsPermitted returns true if userID is permitted to a fileID with the wanted role.
	IsPermitted(context.Context, *IsPermittedRequest) (*IsPermittedResponse, error)
	// DeleteFilePermissions deletes all permissions of a file and returns them.
	DeleteFilePermissions(context.Context, *DeleteFilePermissionsRequest) (*DeleteFilePermissionsResponse, error)
}

// UnimplementedPermissionServer can be embedded to have forward compatible implementations.
type UnimplementedPermissionServer struct {
}

func (*UnimplementedPermissionServer) CreatePermission(ctx context.Context, req *CreatePermissionRequest) (*PermissionObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermission not implemented")
}
func (*UnimplementedPermissionServer) DeletePermission(ctx context.Context, req *DeletePermissionRequest) (*PermissionObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePermission not implemented")
}
func (*UnimplementedPermissionServer) GetPermission(ctx context.Context, req *GetPermissionRequest) (*PermissionObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermission not implemented")
}
func (*UnimplementedPermissionServer) GetFilePermissions(ctx context.Context, req *GetFilePermissionsRequest) (*GetFilePermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilePermissions not implemented")
}
func (*UnimplementedPermissionServer) GetUserPermissions(ctx context.Context, req *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (*UnimplementedPermissionServer) IsPermitted(ctx context.Context, req *IsPermittedRequest) (*IsPermittedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsPermitted not implemented")
}
func (*UnimplementedPermissionServer) DeleteFilePermissions(ctx context.Context, req *DeleteFilePermissionsRequest) (*DeleteFilePermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFilePermissions not implemented")
}

func RegisterPermissionServer(s *grpc.Server, srv PermissionServer) {
	s.RegisterService(&_Permission_serviceDesc, srv)
}

func _Permission_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/CreatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_DeletePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).DeletePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/DeletePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).DeletePermission(ctx, req.(*DeletePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/GetPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetPermission(ctx, req.(*GetPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetFilePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetFilePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/GetFilePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetFilePermissions(ctx, req.(*GetFilePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/GetUserPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetUserPermissions(ctx, req.(*GetUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_IsPermitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsPermittedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).IsPermitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/IsPermitted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).IsPermitted(ctx, req.(*IsPermittedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_DeleteFilePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFilePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).DeleteFilePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/permission.Permission/DeleteFilePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).DeleteFilePermissions(ctx, req.(*DeleteFilePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Permission_serviceDesc = grpc.ServiceDesc{
	ServiceName: "permission.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePermission",
			Handler:    _Permission_CreatePermission_Handler,
		},
		{
			MethodName: "DeletePermission",
			Handler:    _Permission_DeletePermission_Handler,
		},
		{
			MethodName: "GetPermission",
			Handler:    _Permission_GetPermission_Handler,
		},
		{
			MethodName: "GetFilePermissions",
			Handler:    _Permission_GetFilePermissions_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _Permission_GetUserPermissions_Handler,
		},
		{
			MethodName: "IsPermitted",
			Handler:    _Permission_IsPermitted_Handler,
		},
		{
			MethodName: "DeleteFilePermissions",
			Handler:    _Permission_DeleteFilePermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}
